### ISSUE TITLE
起点中文无法自动读取下一章

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#61]
比较奇怪, 如果刚打开脚本, 然后立刻拉到最底下, 能正常读取下一章. 但是正常阅读, 等了一会儿, 就无法读取了, 一直转圈

```
Error: Content Patch Error! SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Parser.contentPatch (小说阅读脚本.user.js:1244:44)
    at Parser.applyPatch (小说阅读脚本.user.js:4138:32)
    at Parser.getAll (小说阅读脚本.user.js:4160:16)
    at Object.loaded (小说阅读脚本.user.js:7731:24)
    at Object.scrollForce (小说阅读脚本.user.js:7637:31)
    at Object.scroll (小说阅读脚本.user.js:7622:27)
    at HttpRequest.finishHandle (小说阅读脚本.user.js:7277:57)
    at HttpRequest.send (小说阅读脚本.user.js:6753:16)

Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.isVipChapter (小说阅读脚本.user.js:1233:44)
    at Parser.hasContent (小说阅读脚本.user.js:4253:29)
    at Parser.preProcessDoc (小说阅读脚本.user.js:4173:21)
    at Parser.getAll (小说阅读脚本.user.js:4164:22)
    at async Object.loaded (小说阅读脚本.user.js:7731:11)
    at async Object.scrollForce (小说阅读脚本.user.js:7637:19)
    at async Object.scroll (小说阅读脚本.user.js:7622:15)
```

**Comment by 821938089** [comment]
请求被WAF防火墙拦截了，已尝试修复

**Comment by letterk** [comment]
7.7.5还是不行, 现在真的恶心, 翻页一快就会触发机器人验证

**Comment by 821938089** [comment]
改成用iframe加载了，应该没问题了
